### ISSUE TITLE
some sugar for the layout munging

### ISSUE THREAD

**Issue by dfhoughton** [existentialmutt/ajax_modal_rails#4]
You should provide a note about the layout magic and maybe some sugar to customize it, so if you have a controller that uses `layout` for non-ajax stuff it falls back to this rather than `nil`. I just put this at the top of one controller:
```ruby
module Foo
  class Bar < Baz
    include OneThing
    include AjaxModalRails::Controller

    layout ->(_) { ajax_modal_request? ? ajax_modal_layout : 'what_is_otherwise_expected' }
```
It took a little poking about in the source code for me to see that this is what I needed to do. Maybe you could provide `non_ajax_layout` or something, so this would have been
```ruby
module Foo
  class Bar < Baz
    include OneThing
    include AjaxModalRails::Controller

    non_ajax_layout  'what_is_otherwise_expected'
```

**Comment by existentialmutt** [comment]
I see your point, but I don't see how adding a method like `non_ajax_layout` makes things any less magical.  I'll add some notes to the documentation that draw more attention to the things the module does to your controller.
